# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'STUDYA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for STUDYA
pod 'naveridlogin-sdk-ios'
pod 'MultiProgressView'
pod 'Kingfisher', '~> 7.0'
pod 'JWTDecode', '~> 3.0'
end
